// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHY4lRF6G5WRMnb5TBK3RfdYSL7iaUTf0',
    appId: '1:213726314861:web:23b9e2d3f70123572dda64',
    messagingSenderId: '213726314861',
    projectId: 'yabut-advmobprog-firebase',
    authDomain: 'yabut-advmobprog-firebase.firebaseapp.com',
    storageBucket: 'yabut-advmobprog-firebase.firebasestorage.app',
    measurementId: 'G-1JFVGMZZ6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjwz6jJ3KjjADqapcba5oUSBmvax-BK3k',
    appId: '1:213726314861:android:2bdb5db943979d902dda64',
    messagingSenderId: '213726314861',
    projectId: 'yabut-advmobprog-firebase',
    storageBucket: 'yabut-advmobprog-firebase.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATvKX9D0-m9nczlvJlsAnXeDnlKgNtrlY',
    appId: '1:213726314861:ios:8f6e024d267bcecf2dda64',
    messagingSenderId: '213726314861',
    projectId: 'yabut-advmobprog-firebase',
    storageBucket: 'yabut-advmobprog-firebase.firebasestorage.app',
    iosClientId: '213726314861-f10remhekmvtkcmjn3otssv9l06uphf2.apps.googleusercontent.com',
    iosBundleId: 'com.example.yabutAdvmobprog',
  );
}
